{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Google maps data info\n",
    "https://support.google.com/business/answer/6263531?hl=en-GB"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting git+https://github.com/m-wrzr/populartimes\n",
      "  Cloning https://github.com/m-wrzr/populartimes to c:\\users\\james\\appdata\\local\\temp\\pip-req-build-qs6khxnk\n",
      "Requirement already satisfied, skipping upgrade: requests in c:\\users\\james\\anaconda3\\lib\\site-packages (from populartimes==2.0) (2.21.0)\n",
      "Requirement already satisfied, skipping upgrade: geopy in c:\\users\\james\\anaconda3\\lib\\site-packages (from populartimes==2.0) (1.19.0)\n",
      "Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in c:\\users\\james\\anaconda3\\lib\\site-packages (from requests->populartimes==2.0) (2.8)\n",
      "Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in c:\\users\\james\\anaconda3\\lib\\site-packages (from requests->populartimes==2.0) (2019.3.9)\n",
      "Requirement already satisfied, skipping upgrade: urllib3<1.25,>=1.21.1 in c:\\users\\james\\anaconda3\\lib\\site-packages (from requests->populartimes==2.0) (1.24.1)\n",
      "Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in c:\\users\\james\\anaconda3\\lib\\site-packages (from requests->populartimes==2.0) (3.0.4)\n",
      "Requirement already satisfied, skipping upgrade: geographiclib<2,>=1.49 in c:\\users\\james\\anaconda3\\lib\\site-packages (from geopy->populartimes==2.0) (1.49)\n",
      "Building wheels for collected packages: populartimes\n",
      "  Building wheel for populartimes (setup.py): started\n",
      "  Building wheel for populartimes (setup.py): finished with status 'done'\n",
      "  Stored in directory: C:\\Users\\james\\AppData\\Local\\Temp\\pip-ephem-wheel-cache-5sbv_o6n\\wheels\\75\\ae\\aa\\56b796466ed114d29102c9f74ec35c9a41b53c69ac5215d58a\n",
      "Successfully built populartimes\n",
      "Installing collected packages: populartimes\n",
      "  Found existing installation: populartimes 2.0\n",
      "    Uninstalling populartimes-2.0:\n",
      "      Successfully uninstalled populartimes-2.0\n",
      "Successfully installed populartimes-2.0\n",
      "Requirement already satisfied: pandas in c:\\users\\james\\anaconda3\\lib\\site-packages (0.24.2)\n",
      "Requirement already satisfied: numpy>=1.12.0 in c:\\users\\james\\anaconda3\\lib\\site-packages (from pandas) (1.16.2)\n",
      "Requirement already satisfied: python-dateutil>=2.5.0 in c:\\users\\james\\anaconda3\\lib\\site-packages (from pandas) (2.8.0)\n",
      "Requirement already satisfied: pytz>=2011k in c:\\users\\james\\anaconda3\\lib\\site-packages (from pandas) (2018.9)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\james\\anaconda3\\lib\\site-packages (from python-dateutil>=2.5.0->pandas) (1.12.0)\n"
     ]
    }
   ],
   "source": [
    "!pip install --upgrade git+https://github.com/m-wrzr/populartimes\n",
    "!pip install pandas"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 89,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "import requests # library to handle requests\n",
    "import json # library to handle JSON files\n",
    "import populartimes # https://github.com/m-wrzr/populartimes\n",
    "import json # library to handle JSON files\n",
    "from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe\n",
    "from datetime import datetime\n",
    "import calendar\n",
    "from IPython.display import display, HTML\n",
    "import matplotlib.pyplot as plt # plotting library\n",
    "%matplotlib inline "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "#import store location data\n",
    "df_storelocations = pd.read_csv(\"https://raw.githubusercontent.com/ninjananjo/Clothing-Store-Competition/master/StoreLocations.csv\")\n",
    "#remove unwanted fields\n",
    "df_storelocations = df_storelocations[['TOWN','NAME','ID','COUNTRY','Address1','Postcode','Host']]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "def getBrand(branch_id):\n",
    "    if branch_id.startswith(\"TS\"):\n",
    "            return(\"Topshop\")\n",
    "    elif branch_id.startswith(\"TM\"):\n",
    "            return(\"Topman\")\n",
    "    elif branch_id.startswith(\"OU\"):\n",
    "            return(\"Outfit\")\n",
    "    elif branch_id.startswith(\"MS\"):\n",
    "            return(\"Miss Selfridge\")\n",
    "    else:\n",
    "            return(\"Unknown\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0 unrecognised stores to be excluded\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>TOWN</th>\n",
       "      <th>NAME</th>\n",
       "      <th>ID</th>\n",
       "      <th>COUNTRY</th>\n",
       "      <th>Address1</th>\n",
       "      <th>Postcode</th>\n",
       "      <th>Host</th>\n",
       "      <th>Brand</th>\n",
       "      <th>findplacefromtext</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>LONDON (OXFORD CIRCUS)</td>\n",
       "      <td>LONDON OXFORD CIRCUS</td>\n",
       "      <td>MS0325</td>\n",
       "      <td>ENG</td>\n",
       "      <td>Ground Floor, 36-38 Great Castle Street</td>\n",
       "      <td>W1W 8LG</td>\n",
       "      <td>TS0001</td>\n",
       "      <td>Miss Selfridge</td>\n",
       "      <td>Miss%20Selfridge,%20W1W%208LG,%20ENG</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>LONDON (OXFORD CIRCUS)</td>\n",
       "      <td>OXFORD CIRCUS</td>\n",
       "      <td>TM7329</td>\n",
       "      <td>ENG</td>\n",
       "      <td>214 Oxford Street</td>\n",
       "      <td>W1W 8LG</td>\n",
       "      <td>TS0001</td>\n",
       "      <td>Topman</td>\n",
       "      <td>Topman,%20W1W%208LG,%20ENG</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>LONDON (OXFORD CIRCUS)</td>\n",
       "      <td>OXFORD CIRCUS</td>\n",
       "      <td>TS0001</td>\n",
       "      <td>ENG</td>\n",
       "      <td>214 Oxford Street</td>\n",
       "      <td>W1W 8LG</td>\n",
       "      <td>TS0001</td>\n",
       "      <td>Topshop</td>\n",
       "      <td>Topshop,%20W1W%208LG,%20ENG</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>LONDON (CITY)</td>\n",
       "      <td>CHEAPSIDE</td>\n",
       "      <td>TS0873</td>\n",
       "      <td>ENG</td>\n",
       "      <td>Unit Msu1</td>\n",
       "      <td>EC2V 6AH</td>\n",
       "      <td>TS0873</td>\n",
       "      <td>Topshop</td>\n",
       "      <td>Topshop,%20EC2V%206AH,%20ENG</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>NEWCASTLE UPON TYNE</td>\n",
       "      <td>NEWCASTLE UPON TYNE OUTFIT</td>\n",
       "      <td>OU0207</td>\n",
       "      <td>ENG</td>\n",
       "      <td>72-76</td>\n",
       "      <td>NE1 7DF</td>\n",
       "      <td>OU0207</td>\n",
       "      <td>Outfit</td>\n",
       "      <td>Outfit,%20NE1%207DF,%20ENG</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>Z USA LOS ANGELES</td>\n",
       "      <td>LOS ANGELES</td>\n",
       "      <td>TM8104</td>\n",
       "      <td>US</td>\n",
       "      <td>189 The Grove Drive</td>\n",
       "      <td>90036</td>\n",
       "      <td>TS1271</td>\n",
       "      <td>Topman</td>\n",
       "      <td>Topman,%2090036,%20US</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>MANCHESTER (TRAFFORD C)</td>\n",
       "      <td>TRAFFORD CENTRE</td>\n",
       "      <td>TS1012</td>\n",
       "      <td>ENG</td>\n",
       "      <td>130-134 Regent Crescent</td>\n",
       "      <td>M17 8AF</td>\n",
       "      <td>TS1012</td>\n",
       "      <td>Topshop</td>\n",
       "      <td>Topshop,%20M17%208AF,%20ENG</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>HAYES</td>\n",
       "      <td>HAYES LOMBARDY RET PARK OUTFIT</td>\n",
       "      <td>OU0201</td>\n",
       "      <td>ENG</td>\n",
       "      <td>Unit 3</td>\n",
       "      <td>UB3 3EX</td>\n",
       "      <td>OU0201</td>\n",
       "      <td>Outfit</td>\n",
       "      <td>Outfit,%20UB3%203EX,%20ENG</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                      TOWN                            NAME      ID COUNTRY  \\\n",
       "0   LONDON (OXFORD CIRCUS)            LONDON OXFORD CIRCUS  MS0325     ENG   \n",
       "1   LONDON (OXFORD CIRCUS)                   OXFORD CIRCUS  TM7329     ENG   \n",
       "2   LONDON (OXFORD CIRCUS)                   OXFORD CIRCUS  TS0001     ENG   \n",
       "3            LONDON (CITY)                       CHEAPSIDE  TS0873     ENG   \n",
       "4     NEWCASTLE UPON TYNE       NEWCASTLE UPON TYNE OUTFIT  OU0207     ENG   \n",
       "5        Z USA LOS ANGELES                     LOS ANGELES  TM8104      US   \n",
       "6  MANCHESTER (TRAFFORD C)                 TRAFFORD CENTRE  TS1012     ENG   \n",
       "7                    HAYES  HAYES LOMBARDY RET PARK OUTFIT  OU0201     ENG   \n",
       "\n",
       "                                  Address1  Postcode    Host           Brand  \\\n",
       "0  Ground Floor, 36-38 Great Castle Street   W1W 8LG  TS0001  Miss Selfridge   \n",
       "1                        214 Oxford Street   W1W 8LG  TS0001          Topman   \n",
       "2                        214 Oxford Street   W1W 8LG  TS0001         Topshop   \n",
       "3                                Unit Msu1  EC2V 6AH  TS0873         Topshop   \n",
       "4                                    72-76   NE1 7DF  OU0207          Outfit   \n",
       "5                      189 The Grove Drive     90036  TS1271          Topman   \n",
       "6                  130-134 Regent Crescent   M17 8AF  TS1012         Topshop   \n",
       "7                                   Unit 3   UB3 3EX  OU0201          Outfit   \n",
       "\n",
       "                      findplacefromtext  \n",
       "0  Miss%20Selfridge,%20W1W%208LG,%20ENG  \n",
       "1            Topman,%20W1W%208LG,%20ENG  \n",
       "2           Topshop,%20W1W%208LG,%20ENG  \n",
       "3          Topshop,%20EC2V%206AH,%20ENG  \n",
       "4            Outfit,%20NE1%207DF,%20ENG  \n",
       "5                 Topman,%2090036,%20US  \n",
       "6           Topshop,%20M17%208AF,%20ENG  \n",
       "7            Outfit,%20UB3%203EX,%20ENG  "
      ]
     },
     "execution_count": 19,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#Add brand column\n",
    "brands = []\n",
    "for branch_id in df_storelocations['ID']:\n",
    "    brands.append(getBrand(branch_id))\n",
    "            \n",
    "df_storelocations.loc[:,'Brand'] = brands\n",
    "\n",
    "#Exclude unrecognised brands\n",
    "print(sum(df_storelocations['Brand'] == \"Unknown\"), \"unrecognised stores to be excluded\")\n",
    "df_storelocations = df_storelocations[df_storelocations['Brand'] != \"Unknown\"]\n",
    "\n",
    "#Add new column with googlemaps search text\n",
    "df_storelocations['findplacefromtext']= df_storelocations['Brand'].str.replace(\" \",\"%20\")\\\n",
    "                                      + \",%20\" + df_storelocations['Postcode'].str.replace(\" \",\"%20\")\\\n",
    "                                      + \",%20\" + df_storelocations['COUNTRY'].str.replace(\" \",\"%20\")\n",
    "#+ \",%20\" + df_storelocations['Address1'].str.replace(\" \",\"%20\")\\    \n",
    "    \n",
    "df_storelocations_rows = df_storelocations.shape[0]    \n",
    "df_storelocations.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [],
   "source": [
    "#GoogleMaps API Credentials\n",
    "\n",
    "#for field definition go to https://developers.google.com/places/web-service/search#PlaceSearchResults\n",
    "#Basic: formatted_address,geometry,icon,id,name,permanently_closed,photos,place_id,plus_code,types,user_ratings_total\n",
    "#Contact: opening_hours, open_now,\n",
    "#Atmospheric: price_level, rating\n",
    "fields='place_id,name,formatted_address,geometry,permanently_closed,plus_code'\n",
    "key='AIzaSyBTqRFNpFXp2r8o0lk6tbGIU92_35caKSU'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>formatted_address</th>\n",
       "      <th>geometry.location.lat</th>\n",
       "      <th>geometry.location.lng</th>\n",
       "      <th>geometry.viewport.northeast.lat</th>\n",
       "      <th>geometry.viewport.northeast.lng</th>\n",
       "      <th>geometry.viewport.southwest.lat</th>\n",
       "      <th>geometry.viewport.southwest.lng</th>\n",
       "      <th>name</th>\n",
       "      <th>place_id</th>\n",
       "      <th>plus_code.compound_code</th>\n",
       "      <th>plus_code.global_code</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Ground Floor, 36-38 Great Castle St, Marylebon...</td>\n",
       "      <td>51.515649</td>\n",
       "      <td>-0.140957</td>\n",
       "      <td>51.517009</td>\n",
       "      <td>-0.139521</td>\n",
       "      <td>51.514310</td>\n",
       "      <td>-0.142221</td>\n",
       "      <td>Miss Selfridge</td>\n",
       "      <td>ChIJZZmpzywFdkgRu2BBVDT3Dmc</td>\n",
       "      <td>GV85+7J London, United Kingdom</td>\n",
       "      <td>9C3XGV85+7J</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>214 Oxford St, London W1C 1DA, UK</td>\n",
       "      <td>51.515514</td>\n",
       "      <td>-0.141265</td>\n",
       "      <td>51.517066</td>\n",
       "      <td>-0.139725</td>\n",
       "      <td>51.514366</td>\n",
       "      <td>-0.142424</td>\n",
       "      <td>Topman</td>\n",
       "      <td>ChIJwcDt38wEdkgRVG87ERhnAZU</td>\n",
       "      <td>GV85+6F London, United Kingdom</td>\n",
       "      <td>9C3XGV85+6F</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>214 Oxford St, Marylebone, London W1C 1DA, UK</td>\n",
       "      <td>51.515685</td>\n",
       "      <td>-0.141638</td>\n",
       "      <td>51.516896</td>\n",
       "      <td>-0.140101</td>\n",
       "      <td>51.514196</td>\n",
       "      <td>-0.142800</td>\n",
       "      <td>Topshop</td>\n",
       "      <td>ChIJAxqaTdUadkgRFkNFlD7KaJw</td>\n",
       "      <td>GV85+78 Marylebone, London, UK</td>\n",
       "      <td>9C3XGV85+78</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>MSU1, 1 New Change, London EC2V 6AH, UK</td>\n",
       "      <td>51.514293</td>\n",
       "      <td>-0.096334</td>\n",
       "      <td>51.515747</td>\n",
       "      <td>-0.094966</td>\n",
       "      <td>51.513048</td>\n",
       "      <td>-0.097666</td>\n",
       "      <td>Topshop</td>\n",
       "      <td>ChIJ41b8t6oEdkgRioXfCB0a1M8</td>\n",
       "      <td>GW73+PF City of London, London, UK</td>\n",
       "      <td>9C3XGW73+PF</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>72-74 Northumberland St, Newcastle upon Tyne N...</td>\n",
       "      <td>54.976135</td>\n",
       "      <td>-1.612228</td>\n",
       "      <td>54.977446</td>\n",
       "      <td>-1.610532</td>\n",
       "      <td>54.974746</td>\n",
       "      <td>-1.613232</td>\n",
       "      <td>OUTFIT</td>\n",
       "      <td>ChIJ5Sn1b8lwfkgR0pmw-Ll-hg4</td>\n",
       "      <td>X9GQ+F4 Newcastle upon Tyne, UK</td>\n",
       "      <td>9C6WX9GQ+F4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>189 The Grove Dr, Los Angeles, CA 90036, USA</td>\n",
       "      <td>34.072011</td>\n",
       "      <td>-118.359099</td>\n",
       "      <td>34.073361</td>\n",
       "      <td>-118.357749</td>\n",
       "      <td>34.070661</td>\n",
       "      <td>-118.360449</td>\n",
       "      <td>Topshop Topman</td>\n",
       "      <td>ChIJWYAZNzC5woARqe_Pu_5D7jw</td>\n",
       "      <td>3JCR+R9 Los Angeles, California, USA</td>\n",
       "      <td>85633JCR+R9</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>The Trafford Centre, 130-134 Regent Cres, Manc...</td>\n",
       "      <td>53.466571</td>\n",
       "      <td>-2.349546</td>\n",
       "      <td>53.467921</td>\n",
       "      <td>-2.348196</td>\n",
       "      <td>53.465221</td>\n",
       "      <td>-2.350896</td>\n",
       "      <td>Topshop</td>\n",
       "      <td>ChIJvUYBYLuue0gRKwHtN1aAiN4</td>\n",
       "      <td>FM82+J5 Stretford, Manchester, UK</td>\n",
       "      <td>9C5VFM82+J5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>Lombardy Retail Park, 3, Hayes UB3 3EX, United...</td>\n",
       "      <td>51.516437</td>\n",
       "      <td>-0.405550</td>\n",
       "      <td>51.517766</td>\n",
       "      <td>-0.403966</td>\n",
       "      <td>51.515067</td>\n",
       "      <td>-0.406665</td>\n",
       "      <td>OUTFIT</td>\n",
       "      <td>ChIJP-ovg2FtdkgRL9DPnlO2wOk</td>\n",
       "      <td>GH8V+HQ Hayes, United Kingdom</td>\n",
       "      <td>9C3XGH8V+HQ</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                   formatted_address  geometry.location.lat  \\\n",
       "0  Ground Floor, 36-38 Great Castle St, Marylebon...              51.515649   \n",
       "1                  214 Oxford St, London W1C 1DA, UK              51.515514   \n",
       "2      214 Oxford St, Marylebone, London W1C 1DA, UK              51.515685   \n",
       "3            MSU1, 1 New Change, London EC2V 6AH, UK              51.514293   \n",
       "4  72-74 Northumberland St, Newcastle upon Tyne N...              54.976135   \n",
       "5       189 The Grove Dr, Los Angeles, CA 90036, USA              34.072011   \n",
       "6  The Trafford Centre, 130-134 Regent Cres, Manc...              53.466571   \n",
       "7  Lombardy Retail Park, 3, Hayes UB3 3EX, United...              51.516437   \n",
       "\n",
       "   geometry.location.lng  geometry.viewport.northeast.lat  \\\n",
       "0              -0.140957                        51.517009   \n",
       "1              -0.141265                        51.517066   \n",
       "2              -0.141638                        51.516896   \n",
       "3              -0.096334                        51.515747   \n",
       "4              -1.612228                        54.977446   \n",
       "5            -118.359099                        34.073361   \n",
       "6              -2.349546                        53.467921   \n",
       "7              -0.405550                        51.517766   \n",
       "\n",
       "   geometry.viewport.northeast.lng  geometry.viewport.southwest.lat  \\\n",
       "0                        -0.139521                        51.514310   \n",
       "1                        -0.139725                        51.514366   \n",
       "2                        -0.140101                        51.514196   \n",
       "3                        -0.094966                        51.513048   \n",
       "4                        -1.610532                        54.974746   \n",
       "5                      -118.357749                        34.070661   \n",
       "6                        -2.348196                        53.465221   \n",
       "7                        -0.403966                        51.515067   \n",
       "\n",
       "   geometry.viewport.southwest.lng            name  \\\n",
       "0                        -0.142221  Miss Selfridge   \n",
       "1                        -0.142424          Topman   \n",
       "2                        -0.142800         Topshop   \n",
       "3                        -0.097666         Topshop   \n",
       "4                        -1.613232          OUTFIT   \n",
       "5                      -118.360449  Topshop Topman   \n",
       "6                        -2.350896         Topshop   \n",
       "7                        -0.406665          OUTFIT   \n",
       "\n",
       "                      place_id               plus_code.compound_code  \\\n",
       "0  ChIJZZmpzywFdkgRu2BBVDT3Dmc        GV85+7J London, United Kingdom   \n",
       "1  ChIJwcDt38wEdkgRVG87ERhnAZU        GV85+6F London, United Kingdom   \n",
       "2  ChIJAxqaTdUadkgRFkNFlD7KaJw        GV85+78 Marylebone, London, UK   \n",
       "3  ChIJ41b8t6oEdkgRioXfCB0a1M8    GW73+PF City of London, London, UK   \n",
       "4  ChIJ5Sn1b8lwfkgR0pmw-Ll-hg4       X9GQ+F4 Newcastle upon Tyne, UK   \n",
       "5  ChIJWYAZNzC5woARqe_Pu_5D7jw  3JCR+R9 Los Angeles, California, USA   \n",
       "6  ChIJvUYBYLuue0gRKwHtN1aAiN4     FM82+J5 Stretford, Manchester, UK   \n",
       "7  ChIJP-ovg2FtdkgRL9DPnlO2wOk         GH8V+HQ Hayes, United Kingdom   \n",
       "\n",
       "  plus_code.global_code  \n",
       "0           9C3XGV85+7J  \n",
       "1           9C3XGV85+6F  \n",
       "2           9C3XGV85+78  \n",
       "3           9C3XGW73+PF  \n",
       "4           9C6WX9GQ+F4  \n",
       "5           85633JCR+R9  \n",
       "6           9C5VFM82+J5  \n",
       "7           9C3XGH8V+HQ  "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "google_json = pd.DataFrame()\n",
    "\n",
    "for store in df_storelocations['findplacefromtext']:\n",
    "    #For request parameters go to https://developers.google.com/places/web-service/search\n",
    "    url=\"https://maps.googleapis.com/maps/api/place/findplacefromtext/json?input={}&inputtype=textquery&key={}&fields={}\".format(store, key, fields)\n",
    "    #print(url)\n",
    "    temp = requests.get(url).json() #Google Places API request   \n",
    "    google_json = google_json.append(json_normalize(temp['candidates'][0])) #takes top response only\n",
    "    \n",
    "google_json.reset_index(drop=True, inplace=True)\n",
    "\n",
    "#Check that the number of rows from Googlemaps matches original store info file.\n",
    "if google_json.shape[0] != df_storelocations_rows: \n",
    "    print(\"Error - Number of rows has changed. df_storelocations:{} vs google_json:{}\".format(google_json.shape[0], df_storelocations_rows))\n",
    "else:\n",
    "    display(google_json.head(10))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 61,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>address</th>\n",
       "      <th>coordinates.lat</th>\n",
       "      <th>coordinates.lng</th>\n",
       "      <th>current_popularity</th>\n",
       "      <th>id</th>\n",
       "      <th>international_phone_number</th>\n",
       "      <th>name</th>\n",
       "      <th>populartimes</th>\n",
       "      <th>rating</th>\n",
       "      <th>rating_n</th>\n",
       "      <th>time_spent</th>\n",
       "      <th>types</th>\n",
       "      <th>ID</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Ground Floor, 36-38 Great Castle St, Marylebon...</td>\n",
       "      <td>51.515649</td>\n",
       "      <td>-0.140957</td>\n",
       "      <td>NaN</td>\n",
       "      <td>ChIJZZmpzywFdkgRu2BBVDT3Dmc</td>\n",
       "      <td>+44 20 7927 0158</td>\n",
       "      <td>Miss Selfridge</td>\n",
       "      <td>NaN</td>\n",
       "      <td>4.1</td>\n",
       "      <td>42</td>\n",
       "      <td>NaN</td>\n",
       "      <td>[clothing_store, store, point_of_interest, est...</td>\n",
       "      <td>MS0325</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>214 Oxford St, London W1C 1DA, UK</td>\n",
       "      <td>51.515514</td>\n",
       "      <td>-0.141265</td>\n",
       "      <td>NaN</td>\n",
       "      <td>ChIJwcDt38wEdkgRVG87ERhnAZU</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Topman</td>\n",
       "      <td>[{'name': 'Monday', 'data': [0, 0, 0, 0, 0, 0,...</td>\n",
       "      <td>4.3</td>\n",
       "      <td>311</td>\n",
       "      <td>[25, 60]</td>\n",
       "      <td>[clothing_store, store, point_of_interest, est...</td>\n",
       "      <td>TM7329</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>214 Oxford St, Marylebone, London W1C 1DA, UK</td>\n",
       "      <td>51.515685</td>\n",
       "      <td>-0.141638</td>\n",
       "      <td>78.0</td>\n",
       "      <td>ChIJAxqaTdUadkgRFkNFlD7KaJw</td>\n",
       "      <td>+44 20 7927 0214</td>\n",
       "      <td>Topshop</td>\n",
       "      <td>[{'name': 'Monday', 'data': [0, 0, 0, 0, 0, 0,...</td>\n",
       "      <td>4.0</td>\n",
       "      <td>3185</td>\n",
       "      <td>[25, 60]</td>\n",
       "      <td>[clothing_store, store, point_of_interest, est...</td>\n",
       "      <td>TS0001</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>MSU1, 1 New Change, London EC2V 6AH, UK</td>\n",
       "      <td>51.514293</td>\n",
       "      <td>-0.096334</td>\n",
       "      <td>NaN</td>\n",
       "      <td>ChIJ41b8t6oEdkgRioXfCB0a1M8</td>\n",
       "      <td>+44 20 7248 0180</td>\n",
       "      <td>Topshop</td>\n",
       "      <td>[{'name': 'Monday', 'data': [0, 0, 0, 0, 0, 0,...</td>\n",
       "      <td>3.9</td>\n",
       "      <td>153</td>\n",
       "      <td>[15, 15]</td>\n",
       "      <td>[clothing_store, store, point_of_interest, est...</td>\n",
       "      <td>TS0873</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>72-74 Northumberland St, Newcastle upon Tyne N...</td>\n",
       "      <td>54.976135</td>\n",
       "      <td>-1.612228</td>\n",
       "      <td>NaN</td>\n",
       "      <td>ChIJ5Sn1b8lwfkgR0pmw-Ll-hg4</td>\n",
       "      <td>+44 191 230 0874</td>\n",
       "      <td>OUTFIT</td>\n",
       "      <td>[{'name': 'Monday', 'data': [0, 0, 0, 0, 0, 0,...</td>\n",
       "      <td>4.2</td>\n",
       "      <td>18</td>\n",
       "      <td>[10, 10]</td>\n",
       "      <td>[clothing_store, shoe_store, store, point_of_i...</td>\n",
       "      <td>OU0207</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>189 The Grove Dr, Los Angeles, CA 90036, USA</td>\n",
       "      <td>34.072011</td>\n",
       "      <td>-118.359099</td>\n",
       "      <td>NaN</td>\n",
       "      <td>ChIJWYAZNzC5woARqe_Pu_5D7jw</td>\n",
       "      <td>+1 323-938-1085</td>\n",
       "      <td>Topshop Topman</td>\n",
       "      <td>[{'name': 'Monday', 'data': [0, 0, 0, 0, 0, 0,...</td>\n",
       "      <td>4.0</td>\n",
       "      <td>257</td>\n",
       "      <td>[15, 15]</td>\n",
       "      <td>[clothing_store, store, point_of_interest, est...</td>\n",
       "      <td>TM8104</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>The Trafford Centre, 130-134 Regent Cres, Stre...</td>\n",
       "      <td>53.466571</td>\n",
       "      <td>-2.349546</td>\n",
       "      <td>105.0</td>\n",
       "      <td>ChIJvUYBYLuue0gRKwHtN1aAiN4</td>\n",
       "      <td>+44 161 746 8703</td>\n",
       "      <td>Topshop</td>\n",
       "      <td>[{'name': 'Monday', 'data': [0, 0, 0, 0, 0, 0,...</td>\n",
       "      <td>3.9</td>\n",
       "      <td>397</td>\n",
       "      <td>[10, 10]</td>\n",
       "      <td>[clothing_store, store, point_of_interest, est...</td>\n",
       "      <td>TS1012</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>3, Lombardy Retail Park, Hayes UB3 3EX, UK</td>\n",
       "      <td>51.516437</td>\n",
       "      <td>-0.405550</td>\n",
       "      <td>NaN</td>\n",
       "      <td>ChIJP-ovg2FtdkgRL9DPnlO2wOk</td>\n",
       "      <td>+44 20 8573 6980</td>\n",
       "      <td>OUTFIT</td>\n",
       "      <td>NaN</td>\n",
       "      <td>3.4</td>\n",
       "      <td>28</td>\n",
       "      <td>NaN</td>\n",
       "      <td>[clothing_store, shoe_store, store, point_of_i...</td>\n",
       "      <td>OU0201</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                                             address  coordinates.lat  \\\n",
       "0  Ground Floor, 36-38 Great Castle St, Marylebon...        51.515649   \n",
       "1                  214 Oxford St, London W1C 1DA, UK        51.515514   \n",
       "2      214 Oxford St, Marylebone, London W1C 1DA, UK        51.515685   \n",
       "3            MSU1, 1 New Change, London EC2V 6AH, UK        51.514293   \n",
       "4  72-74 Northumberland St, Newcastle upon Tyne N...        54.976135   \n",
       "5       189 The Grove Dr, Los Angeles, CA 90036, USA        34.072011   \n",
       "6  The Trafford Centre, 130-134 Regent Cres, Stre...        53.466571   \n",
       "7         3, Lombardy Retail Park, Hayes UB3 3EX, UK        51.516437   \n",
       "\n",
       "   coordinates.lng  current_popularity                           id  \\\n",
       "0        -0.140957                 NaN  ChIJZZmpzywFdkgRu2BBVDT3Dmc   \n",
       "1        -0.141265                 NaN  ChIJwcDt38wEdkgRVG87ERhnAZU   \n",
       "2        -0.141638                78.0  ChIJAxqaTdUadkgRFkNFlD7KaJw   \n",
       "3        -0.096334                 NaN  ChIJ41b8t6oEdkgRioXfCB0a1M8   \n",
       "4        -1.612228                 NaN  ChIJ5Sn1b8lwfkgR0pmw-Ll-hg4   \n",
       "5      -118.359099                 NaN  ChIJWYAZNzC5woARqe_Pu_5D7jw   \n",
       "6        -2.349546               105.0  ChIJvUYBYLuue0gRKwHtN1aAiN4   \n",
       "7        -0.405550                 NaN  ChIJP-ovg2FtdkgRL9DPnlO2wOk   \n",
       "\n",
       "  international_phone_number            name  \\\n",
       "0           +44 20 7927 0158  Miss Selfridge   \n",
       "1                        NaN          Topman   \n",
       "2           +44 20 7927 0214         Topshop   \n",
       "3           +44 20 7248 0180         Topshop   \n",
       "4           +44 191 230 0874          OUTFIT   \n",
       "5            +1 323-938-1085  Topshop Topman   \n",
       "6           +44 161 746 8703         Topshop   \n",
       "7           +44 20 8573 6980          OUTFIT   \n",
       "\n",
       "                                        populartimes  rating  rating_n  \\\n",
       "0                                                NaN     4.1        42   \n",
       "1  [{'name': 'Monday', 'data': [0, 0, 0, 0, 0, 0,...     4.3       311   \n",
       "2  [{'name': 'Monday', 'data': [0, 0, 0, 0, 0, 0,...     4.0      3185   \n",
       "3  [{'name': 'Monday', 'data': [0, 0, 0, 0, 0, 0,...     3.9       153   \n",
       "4  [{'name': 'Monday', 'data': [0, 0, 0, 0, 0, 0,...     4.2        18   \n",
       "5  [{'name': 'Monday', 'data': [0, 0, 0, 0, 0, 0,...     4.0       257   \n",
       "6  [{'name': 'Monday', 'data': [0, 0, 0, 0, 0, 0,...     3.9       397   \n",
       "7                                                NaN     3.4        28   \n",
       "\n",
       "  time_spent                                              types      ID  \n",
       "0        NaN  [clothing_store, store, point_of_interest, est...  MS0325  \n",
       "1   [25, 60]  [clothing_store, store, point_of_interest, est...  TM7329  \n",
       "2   [25, 60]  [clothing_store, store, point_of_interest, est...  TS0001  \n",
       "3   [15, 15]  [clothing_store, store, point_of_interest, est...  TS0873  \n",
       "4   [10, 10]  [clothing_store, shoe_store, store, point_of_i...  OU0207  \n",
       "5   [15, 15]  [clothing_store, store, point_of_interest, est...  TM8104  \n",
       "6   [10, 10]  [clothing_store, store, point_of_interest, est...  TS1012  \n",
       "7        NaN  [clothing_store, shoe_store, store, point_of_i...  OU0201  "
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "#df_populartimes = populartimes.get_id(key,'ChIJAxqaTdUadkgRFkNFlD7KaJw')\n",
    "\n",
    "df_populartimes = pd.DataFrame()\n",
    "\n",
    "for place_id in google_json.loc[:,'place_id']:\n",
    "    populartimes_json = populartimes.get_id(key,place_id)\n",
    "    df_populartimes = df_populartimes.append(json_normalize(populartimes_json), sort=True)\n",
    "\n",
    "df_populartimes.reset_index(drop=True, inplace=True)\n",
    "df_populartimes = df_populartimes.merge(df_storelocations['ID'],left_index=True, right_index = True)\n",
    "\n",
    "#Check that the number of rows from PopularTimes matches original store info file.\n",
    "if df_populartimes.shape[0] != df_storelocations_rows: \n",
    "    print(\"Error - Number of rows has changed. df_storelocations:{} vs df_populartimes:{}\".format(df_populartimes.shape[0], df_storelocations_rows))\n",
    "else:\n",
    "    display(df_populartimes.head(10))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 62,
   "metadata": {},
   "outputs": [],
   "source": [
    "def getNormalPopularity(placeId, day, hour):\n",
    "    try:\n",
    "        dayname = calendar.day_name[day]\n",
    "        temp1 = df_populartimes[df_populartimes['id']==placeId]\n",
    "        temp2 = json_normalize(temp1['populartimes'][temp1.index.values[0]], errors = 'ignore')\n",
    "        temp3 = temp2[temp2['name']==dayname]\n",
    "        temp4 = temp3['data'].values\n",
    "        normalPopularity = temp4[0][hour]\n",
    "        #print(placeId, dayname, hour, temp3)\n",
    "        return(normalPopularity)\n",
    "    except:\n",
    "        return(None)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 63,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "[None, 32, 47, 46, 48, 68, 67, None]"
      ]
     },
     "execution_count": 63,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "timezone = 0 #set 1 for BST and 0 for GMT\n",
    "normal_popularity = []\n",
    "\n",
    "for id in df_populartimes['id']:\n",
    "    normal_popularity.append(getNormalPopularity(id, datetime.today().weekday(), datetime.today().hour + timezone))\n",
    "    \n",
    "normal_popularity"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 67,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>branch_id</th>\n",
       "      <th>place_id</th>\n",
       "      <th>name</th>\n",
       "      <th>address</th>\n",
       "      <th>rating</th>\n",
       "      <th>time_spent</th>\n",
       "      <th>coordinates.lat</th>\n",
       "      <th>coordinates.lng</th>\n",
       "      <th>current_popularity</th>\n",
       "      <th>normal_popularity</th>\n",
       "      <th>popularity_variance</th>\n",
       "      <th>current_datetime_gmt</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>MS0325</td>\n",
       "      <td>ChIJZZmpzywFdkgRu2BBVDT3Dmc</td>\n",
       "      <td>Miss Selfridge</td>\n",
       "      <td>Ground Floor, 36-38 Great Castle St, Marylebon...</td>\n",
       "      <td>4.1</td>\n",
       "      <td>NaN</td>\n",
       "      <td>51.515649</td>\n",
       "      <td>-0.140957</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>2019-05-05 15:49</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>TM7329</td>\n",
       "      <td>ChIJwcDt38wEdkgRVG87ERhnAZU</td>\n",
       "      <td>Topman</td>\n",
       "      <td>214 Oxford St, London W1C 1DA, UK</td>\n",
       "      <td>4.3</td>\n",
       "      <td>[25, 60]</td>\n",
       "      <td>51.515514</td>\n",
       "      <td>-0.141265</td>\n",
       "      <td>NaN</td>\n",
       "      <td>32.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>2019-05-05 15:49</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>TS0001</td>\n",
       "      <td>ChIJAxqaTdUadkgRFkNFlD7KaJw</td>\n",
       "      <td>Topshop</td>\n",
       "      <td>214 Oxford St, Marylebone, London W1C 1DA, UK</td>\n",
       "      <td>4.0</td>\n",
       "      <td>[25, 60]</td>\n",
       "      <td>51.515685</td>\n",
       "      <td>-0.141638</td>\n",
       "      <td>78.0</td>\n",
       "      <td>47.0</td>\n",
       "      <td>31.0</td>\n",
       "      <td>2019-05-05 15:49</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>TS0873</td>\n",
       "      <td>ChIJ41b8t6oEdkgRioXfCB0a1M8</td>\n",
       "      <td>Topshop</td>\n",
       "      <td>MSU1, 1 New Change, London EC2V 6AH, UK</td>\n",
       "      <td>3.9</td>\n",
       "      <td>[15, 15]</td>\n",
       "      <td>51.514293</td>\n",
       "      <td>-0.096334</td>\n",
       "      <td>NaN</td>\n",
       "      <td>46.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>2019-05-05 15:49</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>OU0207</td>\n",
       "      <td>ChIJ5Sn1b8lwfkgR0pmw-Ll-hg4</td>\n",
       "      <td>OUTFIT</td>\n",
       "      <td>72-74 Northumberland St, Newcastle upon Tyne N...</td>\n",
       "      <td>4.2</td>\n",
       "      <td>[10, 10]</td>\n",
       "      <td>54.976135</td>\n",
       "      <td>-1.612228</td>\n",
       "      <td>NaN</td>\n",
       "      <td>48.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>2019-05-05 15:49</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>TM8104</td>\n",
       "      <td>ChIJWYAZNzC5woARqe_Pu_5D7jw</td>\n",
       "      <td>Topshop Topman</td>\n",
       "      <td>189 The Grove Dr, Los Angeles, CA 90036, USA</td>\n",
       "      <td>4.0</td>\n",
       "      <td>[15, 15]</td>\n",
       "      <td>34.072011</td>\n",
       "      <td>-118.359099</td>\n",
       "      <td>NaN</td>\n",
       "      <td>68.0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>2019-05-05 15:49</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>TS1012</td>\n",
       "      <td>ChIJvUYBYLuue0gRKwHtN1aAiN4</td>\n",
       "      <td>Topshop</td>\n",
       "      <td>The Trafford Centre, 130-134 Regent Cres, Stre...</td>\n",
       "      <td>3.9</td>\n",
       "      <td>[10, 10]</td>\n",
       "      <td>53.466571</td>\n",
       "      <td>-2.349546</td>\n",
       "      <td>105.0</td>\n",
       "      <td>67.0</td>\n",
       "      <td>38.0</td>\n",
       "      <td>2019-05-05 15:49</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>OU0201</td>\n",
       "      <td>ChIJP-ovg2FtdkgRL9DPnlO2wOk</td>\n",
       "      <td>OUTFIT</td>\n",
       "      <td>3, Lombardy Retail Park, Hayes UB3 3EX, UK</td>\n",
       "      <td>3.4</td>\n",
       "      <td>NaN</td>\n",
       "      <td>51.516437</td>\n",
       "      <td>-0.405550</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>2019-05-05 15:49</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "  branch_id                     place_id            name  \\\n",
       "0    MS0325  ChIJZZmpzywFdkgRu2BBVDT3Dmc  Miss Selfridge   \n",
       "1    TM7329  ChIJwcDt38wEdkgRVG87ERhnAZU          Topman   \n",
       "2    TS0001  ChIJAxqaTdUadkgRFkNFlD7KaJw         Topshop   \n",
       "3    TS0873  ChIJ41b8t6oEdkgRioXfCB0a1M8         Topshop   \n",
       "4    OU0207  ChIJ5Sn1b8lwfkgR0pmw-Ll-hg4          OUTFIT   \n",
       "5    TM8104  ChIJWYAZNzC5woARqe_Pu_5D7jw  Topshop Topman   \n",
       "6    TS1012  ChIJvUYBYLuue0gRKwHtN1aAiN4         Topshop   \n",
       "7    OU0201  ChIJP-ovg2FtdkgRL9DPnlO2wOk          OUTFIT   \n",
       "\n",
       "                                             address  rating time_spent  \\\n",
       "0  Ground Floor, 36-38 Great Castle St, Marylebon...     4.1        NaN   \n",
       "1                  214 Oxford St, London W1C 1DA, UK     4.3   [25, 60]   \n",
       "2      214 Oxford St, Marylebone, London W1C 1DA, UK     4.0   [25, 60]   \n",
       "3            MSU1, 1 New Change, London EC2V 6AH, UK     3.9   [15, 15]   \n",
       "4  72-74 Northumberland St, Newcastle upon Tyne N...     4.2   [10, 10]   \n",
       "5       189 The Grove Dr, Los Angeles, CA 90036, USA     4.0   [15, 15]   \n",
       "6  The Trafford Centre, 130-134 Regent Cres, Stre...     3.9   [10, 10]   \n",
       "7         3, Lombardy Retail Park, Hayes UB3 3EX, UK     3.4        NaN   \n",
       "\n",
       "   coordinates.lat  coordinates.lng  current_popularity  normal_popularity  \\\n",
       "0        51.515649        -0.140957                 NaN                NaN   \n",
       "1        51.515514        -0.141265                 NaN               32.0   \n",
       "2        51.515685        -0.141638                78.0               47.0   \n",
       "3        51.514293        -0.096334                 NaN               46.0   \n",
       "4        54.976135        -1.612228                 NaN               48.0   \n",
       "5        34.072011      -118.359099                 NaN               68.0   \n",
       "6        53.466571        -2.349546               105.0               67.0   \n",
       "7        51.516437        -0.405550                 NaN                NaN   \n",
       "\n",
       "   popularity_variance current_datetime_gmt  \n",
       "0                  NaN     2019-05-05 15:49  \n",
       "1                  NaN     2019-05-05 15:49  \n",
       "2                 31.0     2019-05-05 15:49  \n",
       "3                  NaN     2019-05-05 15:49  \n",
       "4                  NaN     2019-05-05 15:49  \n",
       "5                  NaN     2019-05-05 15:49  \n",
       "6                 38.0     2019-05-05 15:49  \n",
       "7                  NaN     2019-05-05 15:49  "
      ]
     },
     "execution_count": 67,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_currentpopularity = df_populartimes.loc[:,['ID','id','name','address','rating','time_spent','coordinates.lat','coordinates.lng','current_popularity']]\n",
    "df_currentpopularity.loc[:,'normal_popularity'] = normal_popularity\n",
    "df_currentpopularity.loc[:,'popularity_variance'] = df_currentpopularity.loc[:,'current_popularity']-df_currentpopularity.loc[:,'normal_popularity']\n",
    "df_currentpopularity.loc[:,'current_datetime_gmt'] = datetime.strftime(datetime.today(), \"%Y-%m-%d %H:%M\")\n",
    "df_currentpopularity.rename(columns={'id':'place_id','ID':'branch_id'}, inplace=True)\n",
    "df_currentpopularity"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 120,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAARgAAAG/CAYAAACDl8jaAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADl0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uIDMuMC4zLCBodHRwOi8vbWF0cGxvdGxpYi5vcmcvnQurowAAIABJREFUeJzt3XecXFX9//HXO9mQhE4KiIQQQEBaQEhEA0IoCgEUVEBqaBIRECkW9OtPERVRFGkKBEJHARGkCSgQUBCQRJAWeo0UA5JQJJDy+f1xzoSbZTe72ezZ2fJ+Ph7z2J1779w5szP7nnPOPfdcRQRmZiX0qncBzKz7csCYWTEOGDMrxgFjZsU4YMysGAeMmRXjgOkBJB0r6eJFePyZkv5fe5bJeoZuHzCSNpP0d0kzJP1X0p2SRuZ1+0m6owPLMkxSSHor356VdExHPX9bRcTBEfEjAEmjJU1t674k7StpsqQ3JE2V9HNJDZX1AyRdJeltSc9J2rOybkVJ10h6Mf8dhzXa90qSrs7v81RJB7dQlr6Szs1leVnSUZV1jd+rt1oKWUl75jK/LemPkgZU1t0maWZlX48tYD/rSbpJ0quSPjBQbWH21ehx5+XX9JHKsrUl3Zr/P56U9PnW7Ku1unXASFoauA44DRgArAT8EHi3nfbf0PJWTVo2IpYE9gC+L2m79ihPCZJ6t/MuFweOAAYBmwBbA9+orP818B6wArAXcIakdfO6ucCNwBeb2ffFwDP5sTsAx0vacgFlORZYA1gF2BL4VhPvxbIRsWS+/ai5HeUyngXsk5//f8BvGm12WGVfay2gXLOAy4EDF7BNa/dVK99mwOqNljUAV5P+RwYA44CLJa3Z0v5aLSK67Q0YAUxvZt3awExgDvBWbTtgGeBCYBrwHPA9oFdetx9wJ/Ar4L/Aj/PyA4ApwOvATcAqzTznMCCAhsqye4Fv5N9H5fsz8s9Rle1uA34K/COvvxoYkNeNBqY2eq5ngW3y78cCF1fW/R54Oe/nr8C6lXXnA2cAfwLeBrbJy34MLAG8Q/pHfyvfPkz6ZxpY2cfG+e/XpxXv0VHAtfn3JUjhsmZl/UXACY0e05D/jsMqy5bMywZXlo0HLlrAc/8b+Ezl/o+AS5t7r1p4HccDv63cXz2/lqUq79+XF/Lz+xEgmli+UPvKf6/7gOH5NX0kL18vv4eqbPtn4Eft9T/YrWswwOPAHEkXSBojabnaioiYAhwM3BXpW2DZvOo0UsisBmwBjAX2r+xzE+BpYHngJ5J2Br4LfAEYDPwN+F1LBVOyKbAucF+uTl8PnAoMBE4Crpc0sPKwsaQw+zAwO2/bFjeQvrmXB/4JXNJo/Z7AT4ClgHlNyIh4GxgDvBjvf3u+SPrA71Z5/N6kf9RZrSjL5sDD+fc1gTkR8Xhl/b9If6OWqNHP2u/rNblx+ix8OO9/Qc/1XG5unSdp0AKef93qviLiKXJYVrb5aW723Clp9IJeTCs0uS9JQyVNlzS0su2RwF8j4oFG+xAf1OzfrE3aK6k6641UUzkfmEr6p7wGWCGv2w+4o7Jtb1LzaZ3Ksq8At1W2f77R/m8ADqzc70X6Rl+libIMI32DTCfVdqYAh+d1+wD/aLT9XcB+lW+tEyrr1iF9gHuzkDWYRtstm8u0TL5/PnBho23O5/3aWlPP9SXgzsrf8GXg4614b/bP78ugfP9TwMuNtjmo9vevLPtADSYvv4P0BdEP2IhUy3ysmedeOe+jX2XZp4Fn8+9LkmrADaQmzxXATQt4LbcABzda9m9gdP59E1Jg9wX2Bd4EVm/h79NcDabV+8qv88nK+1utwfQhfVl+K//+mfyZavZ1Luytu9dgiIgpEbFfRAwhJfOHgZOb2XwQsBipaVTzHKnvpuaFRo9ZBTglf2tMJ32o1egxH3ieiFguItaOiFot5MONnrel536O9KFY0LfqB0jqLekESU9JeoMURDTaT+PX2JKrgXUkrUb6J50REf9ooRw7AycAYyLi1bz4LWDpRpsuTfoHao29gFVJ5T+DVDObmp/vzEqn6Hfzc9X2/4Hnioi3ImJSRMyOiFeAw4DPSFpa0qcq+6rVvhZY9oi4JyLejIh3I+ICUlN7+1a+rvks5L5OBo6LiBlN7GcWsDOpv+pl4GhS30+bO/Eb6/YBUxURj5K+jWtVwMY99K+SOthWqSwbSvommrebRo95AfhKRCxbufWPiL8vZPFebPS8TT33yo3WzcplfpvUeQrM65gd3Mzz7AnsROpbWYZUq4L5q8sLOsX+A+siYibpg7kXqSZ20QIeT+5IPRv4bEQ8WFn1ONAgaY3Ksg14vwm1QBHxXETsGBGDI2ITUlPzH3ndwfF+s+74iHgdeCnvvzXPVXvdioi/VfZVa1I9XN1XDtu++TU1t7+mmihtsaB9bQ2cmI+SvZyX3VU7OhcRD0TEFhExMCK2JXUNLPDLYeFK1k5Voc54Az5KSuUhlerincDZ+f52pG/wxSqPuRi4ilQFXQV4lNyhRqMmVV72eeAhckcp6Z9212bKM4xmOg5J/wzTSQHQQGp2TOf95sNtpG+WdUhh8ntyp2J+zv+Rvon6AD8gNQc/0EQCDgHuJ327LkE60lGtNp9Pbg5VyjZvWf6bvkOucle22RR4ivSNPayp15+32wp4Ddi8mfWXkvqwlsj7nMH8ndD98roA1mL+Js7a+X1bjNQP9CqVTt8mnusE4HZgufy6XgK2y+s2yfvvld+by4CJC9jXusAbpGbeEvlzVOswXhbYNpe9gRTEbwNrNbMv5W3Xya+zH9C3jftaHvhQ5RbAJ4D+ef3wvK/FSUfznqk9V7v8D9Y7BEreSM2Ly0m1gLfzz7OApfP6xUgdq/8FXs3Llssfjmmk2sn3mf8o0h1NPM8+wIP5A/YCcG4z5RnGAo5MAJsBk/M/1WRgs8q623j/KNIbwLXk8KmU7SXgP/mD8ixNB8ySpCbNm6Rm1lgWImDy/XNJITEd+HBl+RPA7S28JxNJ4fdW5XZDZf0A4I/5/Xoe2LPR46PxrbLuiPy+vU3qjxnRQln65tfyBvAKcFRl3R75n+3t/He9EPhQC/vbM5f5beY/yjeYdFTwzfw3uxv49AL2U/ucVG/PtmZfpJrtW8DQZvY9773O908k9Qe+RepP/MiCXuPC3pSfxDo5SbeRQuKcepelOZJuJdWqOm0ZrWO1daCY2XyURkdvROrfMQN6WCevlSHpAuBm4IiIaO0RH+sB3EQys2JcgzGzYhwwZlZMl+7kHTRoUAwbNqzexTDrcSZPnvxqRDQ3mHOeLh0ww4YNY9KkSfUuhlmPI6nxaS1NchPJzIpxwJhZMQ4YMyumS/fBmC2KWbNmMXXqVGbOnFnvonRa/fr1Y8iQIfTp06dNj3fAWI81depUllpqKYYNG4bUXjMndB8RwWuvvcbUqVNZddVV27QPN5Gsx5o5cyYDBw50uDRDEgMHDlykGp4Dxno0h8uCLerfxwFjVmcvv/wyu+++O6uvvjrrrLMO22+/PY8/3txEeO1v+vTp/OY3ja+w0j7cB2OWjR/fvvsbN67lbSKCz3/+8+y7775ceumlANx///288sorrLlmy5cnmjNnDr17v3/pqtmzZ9PQsHD/1rWAOeSQQxbqca3hGoxZHU2cOJE+ffpw8MHvX4Ryww03ZM6cOey4447zlh122GGcf/75QBrBftxxx7HZZpvx+9//ntGjR/Pd736XLbbYglNOOYVp06bxxS9+kZEjRzJy5EjuvPNOAI499lgOOOAARo8ezWqrrcapp6b55o855hieeuopNtxwQ775zW+26+tzDcasjh566CE23njjhX5cv379uOOOdMmqM888k+nTp3P77bcDsOeee3LkkUey2Wab8fzzz7PtttsyZcoUAB599FEmTpzIm2++yVprrcVXv/pVTjjhBB566CHuv//+9nthmQPGrAv60pe+1Oz9m2++mUceeWTe/TfeeIM330zzgO2www707duXvn37svzyy/PKK68ULacDxqyO1l13Xa644ooPLG9oaGDu3Lnz7jc+VLzEEks0e3/u3Lncdddd9O/f/wP77du377zfe/fuzezZs9tc9tZwH4xZHW211Va8++67nH322fOW3XvvvcyZM4dHHnmEd999lxkzZnDLLbe0ep+f+cxnOP300+fdb6nps9RSS82r4bS3HlGDae+jA+2lNUcZrHuTxFVXXcURRxzBCSecQL9+/Rg2bBgnn3wyu+22G8OHD2eNNdbgYx/7WKv3eeqpp3LooYcyfPhwZs+ezeabb86ZZ57Z7PYDBw5k0003Zb311mPMmDGceOKJ7fHSgC4+J++IESOiNfPBOGCsKVOmTGHttdeudzE6vab+TpImR8SIlh7rJpKZFeOAMbNiHDBmVowDxsyKccCYWTEOGDMrxgFjVkeSOProo+fd/8UvfsGxxx7boWXYb7/9mhxN3B56xEA7s1apw3wNffv25corr+Q73/kOgwYNWuinaMv0DB2p85bMrAdoaGhg3Lhx/OpXv+InP/nJfOuee+45DjjgAKZNm8bgwYM577zzGDp0KPvttx8DBgzgvvvuY6ONNmKppZbimWee4aWXXuLxxx/npJNO4u677+aGG25gpZVW4tprr6VPnz4cd9xxXHvttbzzzjuMGjWKs846q/iMfsWaSJLOlfQfSQ9Vlg2Q9BdJT+Sfy+XlknSqpCclPSBpo1LlMutsDj30UC655BJmzJgx3/LDDjuMsWPH8sADD7DXXntx+OGHz1v3+OOPc/PNN/PLX/4SgKeeeorrr7+eq6++mr333pstt9ySBx98kP79+3P99dfP29+9997LQw89xDvvvMN1111X/LWV7IM5H9iu0bJjgFsiYg3glnwfYAywRr6NA84oWC6zTmXppZdm7Nix8yaAqrnrrrvYc889Adhnn33mzf8CsOuuu843k92YMWPo06cP66+/PnPmzGG77dK/3vrrr8+zzz4LpMmtNtlkE9Zff31uvfVWHn744cKvrGDARMRfgf82WrwTcEH+/QJg58ryCyO5G1hW0oqlymbW2RxxxBFMmDCBt99+u9ltqs2ZxtM11KZh6NWrF3369Jm3ba9evZg9ezYzZ87kkEMO4YorruDBBx/koIMO6pDrQXX0UaQVIuIlgPxz+bx8JeCFynZT87IPkDRO0iRJk6ZNm1a0sGYdZcCAAey2225MmDBh3rJRo0bNm6f3kksuYbPNNmvz/mthMmjQIN56661iR40a6yyHqZvqaWryNO+IGB8RIyJixODBgwsXy6zjHH300bz66qvz7p966qmcd955DB8+nIsuuohTTjmlzftedtllOeigg1h//fXZeeedGTlyZHsUuUVFp2uQNAy4LiLWy/cfA0ZHxEu5CXRbRKwl6az8++8ab7eg/Xu6BlsUnq6hdbrSdA3XAPvm3/cFrq4sH5uPJn0CmNFSuJhZ51dsHIyk3wGjgUGSpgI/AE4ALpd0IPA8sGve/E/A9sCTwP+A/UuVy8w6TrGAiYg9mlm1dRPbBnBoqbKYWX10lk5es7roylPGdoRF/fs4YKzH6tevH6+99ppDphkRwWuvvUa/fv3avA+fi2Q91pAhQ5g6dSoeT9W8fv36MWTIkDY/3gFjPVafPn1YddVV612Mbs1NJDMrxgFjZsU4YMysGAeMmRXjgDGzYhwwZlaMA8bMinHAmFkxDhgzK8YBY2bFOGDMrBgHjJkV44Axs2IcMGZWjAPGzIpxwJhZMQ4YMyvGAWNmxThgzKwYB4yZFeOAMbNiHDBmVowDxsyKccCYWTEOGDMrxgFjZsU4YMysGAeMmRXjgDGzYhwwZlaMA8bMinHAmFkxDhgzK8YBY2bFOGDMrBgHjJkV44Axs2IcMGZWjAPGzIpxwJhZMQ4YMyvGAWNmxThgzKwYB4yZFeOAMbNiHDBmVkxdAkbSkZIelvSQpN9J6idpVUn3SHpC0mWSFqtH2cys/XR4wEhaCTgcGBER6wG9gd2BnwG/iog1gNeBAzu6bGbWvurVRGoA+ktqABYHXgK2Aq7I6y8Adq5T2cysnXR4wETEv4FfAM+TgmUGMBmYHhGz82ZTgZU6umxm1r7q0URaDtgJWBX4MLAEMKaJTaOZx4+TNEnSpGnTppUrqJktsno0kbYBnomIaRExC7gSGAUsm5tMAEOAF5t6cESMj4gRETFi8ODBHVNiM2uTegTM88AnJC0uScDWwCPARGCXvM2+wNV1KJuZtaN69MHcQ+rM/SfwYC7DeODbwFGSngQGAhM6umxm1r4aWt6k/UXED4AfNFr8NPDxOhTHzArxSF4zK6YuNRizjjJ+fL1L0LRx4+pdgo7hGoyZFeOAMbNiHDBmVowDxsyKccCYWTEOGDMrxgFjZsU4YMysGAeMmRXjgDGzYhwwZlaMA8bMinHAmFkxDhgzK8YBY2bFOGDMrBgHjJkV44Axs2IcMGZWjAPGzIpxwJhZMQ4YMyvGAWNmxThgzKwYB4yZFeOAMbNiHDBmVowDxsyKccCYWTEOGDMrxgFjZsU01LsAPdr48fUuQdPGjat3CaybcA3GzIpxwJhZMQ4YMyvGAWNmxThgzKwYB4yZFeOAMbNiHDBmVowDxsyKccCYWTGtChhJvUsXxMy6n9bWYJ6UdKKkdYqWxsy6ldYGzHDgceAcSXdLGidp6YLlMrNuoFUBExFvRsTZETEK+BbwA+AlSRdI+kjREppZl9XqPhhJn5N0FXAK8EtgNeBa4E8Fy2dmXVhr54N5ApgInBgRf68sv0LS5u1fLDPrDlrbBzM2Ig6shoukTQEi4vCFfVJJy0q6QtKjkqZI+qSkAZL+IumJ/HO5hd2vmXUurQ2YU5tYdtoiPO8pwI0R8VFgA2AKcAxwS0SsAdyS75tZF7bAJpKkTwKjgMGSjqqsWhpo09iYfPRpc2A/gIh4D3hP0k7A6LzZBcBtwLfb8hxm1jm0VINZDFiSFERLVW5vALu08TlXA6YB50m6T9I5kpYAVoiIlwDyz+XbuH8z6yQWWIOJiNuB2yWdHxHPteNzbgR8LSLukXQKC9EckjQOGAcwdOjQdiqSmZXQUhPp5Ig4AjhdUjReHxGfa8NzTgWmRsQ9+f4VpIB5RdKKEfGSpBWB/zT14IgYD4wHGDFixAfKZGadR0uHqS/KP3/RXk8YES9LekHSWhHxGLA18Ei+7QuckH9e3V7PaWb10VITaXI+0fGgiNi7HZ/3a8AlkhYDngb2J/UHXS7pQOB5YNd2fD4zq4MWB9pFxBxJgyUtlo/4LLKIuB8Y0cSqrdtj/2bWObR2JO+zwJ2SrgHeri2MiJNKFMrMuofWBsyL+daLdJjazKxFrQqYiPhh6YKYWffTqoCRNJg0TcO6QL/a8ojYqlC5zKwbaO25SJcAjwKrAj8k9cncW6hMZtZNtDZgBkbEBGBWRNweEQcAnyhYLjPrBlrbyTsr/3xJ0g6kDt8hZYpkZt1FawPmx5KWAY4mTdOwNHBksVKZWbfQ2qNI1+VfZwBbliuOmXUnLZ3seBrQ7AmFbZnNzsx6jpZqMJM6pBRm1i21dLLjBR1VEDPrflo70G4iTTSVPNDOzBaktUeRvlH5vR/wRWB2+xfHzLqT1h5Fmtxo0Z2Sbi9QHjPrRlrbRBpQudsL2Bj4UJESmVm30dom0mRSH4xITaNngANLFcrMuofWNpFWLV0QM+t+WttE6gccAmxGqsncAZwRETMLls3MurjWNpEuBN7k/cvF7kG64oAn5jazZrU2YNaKiA0q9ydK+leJAplZ99Ha+WDukzRv/hdJmwB3limSmXUXra3BbAKMlfR8vj8UmCLpQSAiYniR0plZl9bagNmuaCnMrFtq7WHq5yRtAHwqL/pbRLgPxswWqFV9MJK+Tpr4e/l8u1jS10oWzMy6vtY2kQ4ENomItwEk/Qy4i/cPW5uZfUBrjyIJmFO5PycvMzNrVmtrMOcB90i6Kt/fGZhQpkhm1l20tpP3JEm3kU4VELB/RNxXsmBm1vW1NOl3P+Bg4CPAg8BvIsITTZlZq7TUB3MBMIIULmOAXxQvkZl1Gy01kdaJiPUBJE0A/lG+SGbWXbQUMLVLxhIRsyUfODJrF+PH17sETRs3rl1311LAbCDpjfy7gP75vkjnIC3drqUxs26lpesi9e6ogphZ99PagXZmZgvNAWNmxThgzKwYB4yZFeOAMbNiHDBmVowDxsyKccCYWTEOGDMrxgFjZsU4YMysGAeMmRXjgDGzYhwwZlZM3QJGUm9J90m6Lt9fVdI9kp6QdJmkxepVNjNrH/WswXwdmFK5/zPgVxGxBvA66WJvZtaF1SVgJA0BdgDOyfcFbAVckTe5gHTtJTPrwupVgzkZ+BYwN98fCEyvXBJlKrBSPQpmZu2nwwNG0o7AfyJicnVxE5tGM48fJ2mSpEnTpk0rUkYzax/1qMFsCnxO0rPApaSm0cnAspJqcwQPAV5s6sERMT4iRkTEiMGDB3dEec2sjTo8YCLiOxExJCKGAbsDt0bEXsBEYJe82b7A1R1dNjNrX51pHMy3gaMkPUnqk5lQ5/KY2SJq6bpIRUXEbcBt+fengY/Xszxm1r46Uw3GzLoZB4yZFeOAMbNiHDBmVowDxsyKccCYWTEOGDMrxgFjZsU4YMysGAeMmRXjgDGzYhwwZlaMA8bMinHAmFkxDhgzK8YBY2bFOGDMrBgHjJkV44Axs2IcMGZWjAPGzIpxwJhZMQ4YMyvGAWNmxThgzKwYB4yZFeOAMbNiHDBmVowDxsyKccCYWTEOGDMrxgFjZsU4YMysGAeMmRXjgDGzYhwwZlaMA8bMinHAmFkxDhgzK8YBY2bFOGDMrBgHjJkV44Axs2IcMGZWjAPGzIpxwJhZMQ4YMyvGAWNmxThgzKwYB4yZFdPhASNpZUkTJU2R9LCkr+flAyT9RdIT+edyHV02M2tf9ajBzAaOjoi1gU8Ah0paBzgGuCUi1gBuyffNrAvr8ICJiJci4p/59zeBKcBKwE7ABXmzC4CdO7psZta+6toHI2kY8DHgHmCFiHgJUggBy9evZGbWHuoWMJKWBP4AHBERbyzE48ZJmiRp0rRp08oV0MwWWV0CRlIfUrhcEhFX5sWvSFoxr18R+E9Tj42I8RExIiJGDB48uGMKbGZtUo+jSAImAFMi4qTKqmuAffPv+wJXd3TZzKx9NdThOTcF9gEelHR/XvZd4ATgckkHAs8Du9ahbGbWjjo8YCLiDkDNrN66I8tiZmV5JK+ZFeOAMbNiHDBmVowDxsyKccCYWTEOGDMrxgFjZsU4YMysGAeMmRXjgDGzYhwwZlaMA8bMinHAmFkxDhgzK8YBY2bFOGDMrBgHjJkV44Axs2IcMGZWjAPGzIpxwJhZMQ4YMyvGAWNmxThgzKwYB4yZFeOAMbNiHDBmVowDxsyKccCYWTEOGDMrxgFjZsU4YMysGAeMmRXjgDGzYhwwZlaMA8bMinHAmFkxDhgzK8YBY2bFOGDMrBgHjJkV44Axs2IcMGZWjAPGzIpxwJhZMQ4YMyvGAWNmxThgzKwYB4yZFeOAMbNiOlXASNpO0mOSnpR0TL3LY2aLptMEjKTewK+BMcA6wB6S1qlvqcxsUXSagAE+DjwZEU9HxHvApcBOdS6TmS2CzhQwKwEvVO5PzcvMrItSRNS7DABI2hXYNiK+nO/vA3w8Ir7WaLtxwLh8dy3gsQ4taPsaBLxa70JYXXT1936ViBjc0kYNHVGSVpoKrFy5PwR4sfFGETEeGN9RhSpJ0qSIGFHvcljH6ynvfWdqIt0LrCFpVUmLAbsD19S5TGa2CDpNDSYiZks6DLgJ6A2cGxEP17lYZrYIOk3AAETEn4A/1bscHahbNPWsTXrEe99pOnnNrPvpTH0wZtbNOGDMrBgHjJkV44Axs2IcMGZWjAPGzIpxwJhZMQ4YMyvGAdPDSVK9y2DdlwPGlql3Aaz7csD0YJK2A86TtLQkfxa6MUmr1ON5/aHqoSRtC/wEOC0i3sCfhW5L0hjgOkkbd3ST2B+qHkjSVsCvgG9ExK2ShgI/ljSgzkWzdiZpG+AE4OiImBwdfHazA6Zn+izw74iYmMPlcuC5iPgvuOO3O5DUS1JfYD/gpIj4s6SlJK0saVdJq3REs9jTNfRQks4D+pHmNT43Ik6vrFshIl6pW+FskUnqGxHvSvo+MB24CzgIWA7YDLgOuCrPwVSMazA9hKRRknaR9FmAiNgfeBmYAVxU2W4scImkxV2T6ZokrQHcJmkQ8HdgQ1KgQJro6qPAW0DxOYEdMD1A7WgRsAlwqaSjASLiSOAZ4KRcfd4LOAT4ekT8r6Pb69ZungbuAX4L3BsRBwBbRsQ44JaImAE8CwyW1FDyi8RNpG5O0iaki9h9OSJukTQSOB7YMyKm5Q/XWaRvucXy8kfqV2KTpEUN93yl1OOBUcCuEfFybb+SDgC+DuweEVPaocjNcg2mG5O0MjAaeAB4R1K/iLgXmAlsKWmXSMYBV5A+cA6XOqnUJBZvw2NHSBotqQEgIuYA3wXuAC6TNBjoL+nLwFeBvUqHC7gG021J2hH4CrA/sAewAamv5QukS/JeA3wOeAiYHBE/qFNRrSI3Z8eRmq5/B67Nl1Ju6XEHkd7rY4A7c8DUajI/AiIi/k/S2sDrEfFyqdcwX7kcMN1PHkT3S2DviLg/LzsK+AwwANg8ImZKWo7U4Tc1Il5odofWISR9nDz4EdgIWAp4BfhlLTCaeMyngDWBc4EDgV1I417+VgmZzwLbRMTXi7+IRtxE6qTa2vGWvwHPBZYGnqotj4iTgD8ADwMjJQ2MiNcj4i6HS/1JWgn4OfBgRFyTf/8LsDawYjOPGQNMIF1HbMOIOAe4HvgOsKmkJfOmywEr1uPIYKe6LpLN18G3OPD2Qj52U3IHLrAucKukPSPiCYCIOFvS4sDXgHOAP7dr4W1RzATuBPaSdGVE3AHcKOlIci2zurGkjwGnAgdGxF9ryyPiNElBeo+fl/Q/YGfgSxHxvw56LfM4YDqZ3Mu/HTBOUqvb4fkb8OPAPhHxsKQ7SN9cl+SQeTLv/xRJ7wEPln0ltiCVIzrDgYGkw8YnAv8GviNpPKl/bAhpeO+KAAARpUlEQVTw3yZ2sRJwU0T8tbKvhoiYHRGnS5pECqaVgS/UvmQ6mgOmk8nt8KN5vx0+Clhd0oLa4YOA7wGPk9rstaMIP8nfZr+VtEdEPJXXnVH+ldiC5EAYA/wamAiMJDWL/kb6YphAOgK0f0T8s4lD1/8DPlQZ7h/A3NwE+jQwKSLu7qCX0yz3wXQibWmHA0TEq6RL7q4F7ClpWGXd8aS+lxslrVqs8NZqSpYlHeXbNyIOBP4P2Jr0Pv8U+D7wHvBO5XH9K7t5FVgF2CAi5krqFRFzcwiNBLbPz1PX0dgOmM6l1g7/gqTN8mjaG4EPk6q785E0XNIogIi4ljRadwPgs5JWq2z6c8C1lk4ijz2aThquv2Zedi0wCfhm3uwPwGTg2zlYtgfOkXSlpLUj4gHgSuBPkjYC+gJI2gfYC7grP09dDxP7MHUdNdMOf53USbsD6byRh0hjVvaJiH9WHrs88ALQh1SdnpK3Ww3YltRc+pOPENVfrXaRf18RaIiIFyR9hdRHclVETM5BcRSpWTQrD46bDXwS+DEpfPYGPkTqV3lH0jGks+PfBF7M2+4SEQ938MtskgOmzppph/+LNAjuSFI7/PiI+EclkD6Uh37vAPyQFExXkT6cfwa2AqaRvhFPi4jXOvhlWZYDZWREXJPf65OAl0g11e8DPwOGArNIp2t8PyKuqjx+KHAz8LvaYEhJF5K+PC6tbDOEVIt5sjN9qbiTt05y23gZ3m+H/y0PiPoC8B9SO/x10lD/ajt8R+AYSV+IiOvzEaFfkL69tgDWAFYghdUmpM5iq5/RwO5Kk3ntCIwFngfuBuZGxLckrUtq2p4SEZMqXyTLRMTzkn5D6uj/XO6bW4J0OPurpPf3hYj4ez1eXIsiwrc63oCLSWMZavcPJXXs9iIFxbfzNv1JTZ+7gO3ytovln58jHXbetbKf/sDy9X59vgWkJu+VpFrmoLxsOeAJ4DfNPGZl4AZgU1JF4GDgTOBa4BbSOKfjgZPzfpYmt0g6063uBegpN6BX5fcVgZXz718hta83zvc3yoHSJ98fnD+Mm5AmDto6L18duAkYnO/vCPwT2K/er9W3gPe7H1YDBHyeNCfLLpWQGUiqzazb6PPRH1iWNHXG1aTxTQ35/r+AnRs911L1fr3N3dxE6gC1djgwXztcUrUd/k1J1Xb4LICImJb3sSxwI7BcPgx9Nmmg1bS83XX5TNpvSPoD8FbkT591vIgISbV+tK9HxFWSlgG+CISkv0aaLmO1iJhde5ykT5NC6BxSbWUO8APgRxHxG0lzgW0kLRERl+SHvdWRr22h1DvhesKNdDbz1aT5Ua8ghc0KpDNmf5i3WZdUlR6R79e+AUeR+mUGkZpC40l9NIc32m5NUiffEvV+vb4FpC+Kh4CP5vuLk474fTp/FnbN96s1lx2Ax4DdgBXzsuVItdzreb8mcyTpNIEl6/06W7q5BtMBIuJ3uVN3F1J1+ZmIeDUflvyHpMERcQjpRMTaYyJ36P6cdPLi3aQ2+SxSe3tmpTPwQGBfYKeIeL1jX51VVUbcrgI8CfSW9B3Skb01SMFzOfBE5FpqftxQ0hHBr0TEbbXlEfG6pMvy3f8jfR5OJTWLOm/NJfNAu4JqoyjzoLffkeZj6QOMljQoh8EngB0lrVsZ9o2kT5KODh0QEb+IiBfzB/JW0lSIw4ED88CqA4BDHS71UxkxOzD/vAl4jfSe/4f0BXAlsGlEXBJ5Go2KucBjEXFbHoDbq7bPSIPybiQdrj6c1D83vewrah+uwRSUaxcL3Q7PVgQmRMTdkvpEGnjVO9JM8TeRzj35Mmni5k+HZ6Krq/xebwd8T9KjpKbOIRHxLqQZ50ijcS9tZhezgQ0kfTIi7iJ9PnoDcyStRer0PR+4KCJmFn457cY1mIIkbUg6lPjViHhAaaqES0hNnrGkmkwf0rdXYx8CPq10hmytKl3bblXSQK2TSd+IDpc6U5rreH9Sh+xNwPLAryUNyOt+S7rQ3T+aeGyvSDPM/Z70nq8O805YhXSEcHfgna5Sc6lxwBRQqS43bodfTRqzcC+VdnjkYeSN/IXUCTwyf5NB6r+B1CT6RERMjIhnC70MayWls9knAL0j4hbgj6TO+F7AOqTTOHaLiOvy9vOdgFh5/yeSRuSOlTQ6b7sf6f0+q4labqfngGlH7dAOr3qONIJ3LPBJpQtpzZW0O2nAXfEJm61puY9kXkhEOpv958BWShOpz4o0/0oDsGpEvNXova71zfXKP/vk/fwVuJB00utZki4hHUHaPSIe7YjX1t58LlI7q7XDgVo7/NRG7fCLgbFNVZUr+6j1ufQnzdG6FLAecBvpxLY9IsITRtVZbvqsS5qa9D5gc1LH/ARSh+xFwGFRmXFO0tbAdqQ+lbnAMflIUa9qTVbSQNIYmF6RL+nbFTlg2lH+wH2DVD0eQBq3sBzwLdLI20uAo2pV5fyYDUl9Kv2AFyPi9rx8sYh4L3+7DSId5nwFeDoinu64V2U1ktYB1o+Iy5QmVj+TVCMdSWrSXkWaVuM80pfBNyPi0Vp45MecChxHGq27KSmUdsjb1b5Y5gubLq3eA3G6y40UAg8AV+T7fUjjHs4lXQt4SdLEzNXHbA88ApxCmv/jQeDHlfUN9X5dvs17L9Yk1VIOzPfP4v1zwjYmXRrkq/n+50hTne6Q7ysvu58UUNX9/pLU17Z0vV9jkb9bvQvQVW/5Q6NGy/YmzZ+6S2XZhaS5XBo/fsf8Idyismw90kxlx9X79fk233u1Fqlz/qeVZWfmcOiV729PmlpjyXx/D+B2UvNWefvXKo/vX/n9ItJ8vJ3uZMVFvbmTt40ikzRS0n5K16f5IylkjpN0tKQNSCM3n6s+Vul6ROeQ5k29PfcZNkTEQ6Sm0A5Kc/NaneVm0cWkOXdmSNo8r/pt/vnF/PNpYAap5kpE/I5Ug3kzf1QOBv4s6V/5vX4nD1uAPAF75LTpThwwC0nSOpK+lH/flnS4eX1SZ+yRpLNjvw8cSzpLerdIM7/P+1tHGnE7FthE0pfzB3B2PlnxMdKRp8Ed+LKsCbmT/dek8Ua7kM4n2iH3td1FmjVwV0k3kj4H58b8o6nXlbStpK0AImIPUpN4Uu5vqV1GZA7wVuOjU92BR/IuBElrkjpqT8+LvkBqd98oaWPS9Wc+FRFnKE0EdQypc/dR0sjMoaTw6BURf5Y0B/ilpLkRcW6kcQ6zJT0LvNuxr84ay7WMPSJfZjUfNt6LFDazIuIsSZcCHwNeiYgp0rzzw7YDfkWaVXB5ScMj4uSI2CPv515gQ6VJxg4kTYHZ7WowdW+jdZUbi94OH0Pq5PsD6RtxaN5my7y81nk4ljTnx5B6v2bf5nv/a+/xGqSjQMeTLsHb1LafJtVU1iJddfFzpMPXDZVtLiWdHjAJWKfer6/UzU2kVljUdjhp2sT/BxxEmsdlNmliKSJiIuk6SF+RdDnpwud7RcR8V/Kz+op82DjSALoLScGxY+5Pa2w90vCEaZGG+99LmhJzG6X5gIiI3UlN6AOiG5/q4XEwLcjt8D+ROmWvI4VBX9K8LveThnFvTZpC4cOk+V3+UHl8A2nU7VMRsV1edlje9jjStJdvSPoMqUq9e3gQXacnaQ2YFzhNrT+W1IT+DOkM6N1Jn5ePkuZPvjgizu+IstaTA6YVlGfxz7+vRWqH9yXN9H5/PkP6A+3w6uNJJyf+MSKOlnQWabj/c6SO9vNJIz9fiS50pqy9Lx9FXIXU53Z2RLwo6RukL6QpEbFV3m4xYB/ghoh4sW4F7iAOmIVQGZG5BulD0gDcGJWh4JVtP0KaHGqZSGdSDwT+kZc9TAqptUiDtLYBjoyIVzropVg7UpqS4+ekPrmtSc3kx0hXhtgPOALYKiL+U68y1osDpo1ygBxEGkT106gcnsxHBo4jTcK9BalDbwLpCNLdwM0RcXhl+76Rz1eyriVPrXAlqS9lcl62HamGOi0ijs/NpQOA0dHDTvPwYeo2iognJZ2Tf6+GyyjS+SZ7RJosaj1SEB1Bmuz7U6RpMvtFxLj8sPc6tvTWjpYknUM2ufZFEWnYQgPpOuHLRsSxknrkF4iPIi2CiHii1slXGSC1EXBpDpfFIo3OPQVYjHRJkddI5yZ9QtLyjftrrGvIfXGQZvSfAxBptsHaEcTrSJNO7Zvv/7Sn1V7AAdOels4/3yUfpgbm5gB5mnR4eqyktSLiJdKJj/9xuHQ9eQT3BElDI+IpYJk8eI5IZ0PXWgZ30+g0kZ7GAdMOlK5l8yOlmeeeBPaTtEmkkbl9lObS/SfwN9LJjPPGVVjXonQ98B8B342I5/PiMcBHJF2sdL2i2ZJ2BXaicqWInsgBs4hyh97PgasiYk4eOPd94ERJIyPivYiYI2lP0vSJ/pt3UZJWJvWj3Rzp/LKVJJ1GqrFuRZqo/dJ8btIxwN7NjZPpKdzJuwjySW/nkc5HmpjPNdqQNHlzA3CDpN+TjjRtTTrfZFrdCmxtJmnFiHhB0unAypK+QhqqcFmlk39rSUNI/W1v+r32t+miWpJ0naJZkoaTpmsYFBHTIuJU0vSWt5La4tt6hG7XJGkwcKPS5N5XkprBhwJPRsRpeZvFACJiakQ87XBJXINpg9wO3zwivp1H6e5AOtHxjIg4Nx9RUqTr21gXVTnCN4s0hqkhIv4t6UpSrXR9STtHxB8jTW/qI4KNuAazkPI5Q8eSLjFRO6Hxj6QO3H/ncQ9BujCadW0rw7wrK/6LNE0Dka4icF1eNqY2P5DD5YNcg1kIeRDdlcCWEXGvpFWA4RFxraQBwCeBpSRdnse7WBclaSXgbElvAy+Tzo5+p7a+UpPpD4ySdH10gWtFdzQHzMLpSzr1fqikp4DLgN8ARMSlkmaTDlm+J+k8H4ru0maQpj/9OOliaKOAYyT1I9Vsfk0KnLOBvg6XpvlcpBZU29WS+pIuVn8kaTTuMRFxTh7nMidv83ng7z5xsWvKR4FmAktExHOV5euTJgs7inSkcAXSZGGfivmnybQK12Ba9lFgSj6T+l1J95JmpFuSfIW+PM6lT6Qr+l1Vz8Ja20naiTR+5RVgRUk3AD+PiP9FxIN5fMsT8f4lYPt5eo0Fc8AsQP42uz/PNPdAbva8Kun2vMnXJC0dEb+M9y9Qb12QpC1Jlw7Zg3SlxuVJM9f1kXRsfn8HkMa+fC8/rEeewLgwfBRpwWaRZo9/j3RU6M78LffRiLiNdBLj1pK+Xr8iWjsZRbrM72RgZkQ8DnyJ1Kf2nbzNdcCcfEqIjxq1gvtgGmliNrpdSJd+3ZJ0idDDgdVInbt/B5YBnukJs5N1R7X3W9IZpBkFj83jmHrlpu9w0vQbOwFDSSN0n61jkbsU12A+qPHf5E+kIBkETAdGAGcAe5KuAPCIw6XrqnyZXAFsJmnj2jimPPXCq6Srdc6NiAcdLgvHfTAVkrYB9pf0L+D+iPhzRPxP0uvAtaQLbx0WEddIuoL0ofMRhO7hbtIlZ74kidxUmitpM9IYGP+vtIGbSFme4+N40tiWQaSmz09r31iSbgYejIgjq4elrfvIg+u+TDozutb3tgtpdsJ/1bNsXZWbSMwLl6uBoyLi56TBU0uQaiw140nVZgEeQNcNRcS/SVNvfI907ar/Ap93uLRdj6/B5HD5ETk0IuITefmfSUeR7iddnPxZUshs4WaRWev06BpMDpfTgS/nYHlB0r2STiTN6XEV8DrpCgHbANs4XMxar8fWYPJZ0ReRzoL+QUQ8nJefR5qouV9EvJeXLQX0jx54XRuzRdEjA0bS1qRDzT8knVOyPOkCarfl9ZeRTmjbwiN0zdqupwbMSKBPRPw9X35ib9JhyJsqIXMDsHhEbFG/kpp1bT0yYGr0wUvB9iFdM/ivef1K+ciCmbVBjw6YqhwyewIDSRM53+kpEM0WTY8+ilSVLy9xGfAS8Hhe5nAxWwSuwTRSm9el3uUw6w4cMGZWjJtIZlaMA8bMinHAmFkxDhgzK8YBY2bFOGDMrBgHjJkV44Axs2IcMGZWzP8HQJgHiIuHfIcAAAAASUVORK5CYII=\n",
      "text/plain": [
       "<Figure size 288x432 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "#Create bar plot\n",
    "df_bar = df_currentpopularity.dropna(subset=['current_popularity'])\n",
    "df_bar = df_bar.merge(df_storelocations, left_on='branch_id', right_on='ID')\n",
    "df_bar['Store Name'] = df_bar['Brand'] + \"\\n\" + df_bar['NAME']\n",
    "df_bar = df_bar.sort_values('popularity_variance', ascending = False)\n",
    "fig, ax = plt.subplots()\n",
    "index = np.arange(0,df_bar.shape[0])\n",
    "bar_width = 0.30\n",
    "opacity = 0.4\n",
    "\n",
    "rects1 = ax.bar(index, df_bar['current_popularity'], bar_width,\n",
    "                alpha=opacity, color='b',               \n",
    "                label='Current')\n",
    "\n",
    "rects2 = ax.bar(index + bar_width, df_bar['normal_popularity'], bar_width,\n",
    "                alpha=opacity, color='r',               \n",
    "                label='Normal')\n",
    "\n",
    "fig.set_figheight(6)\n",
    "fig.set_figwidth(df_bar.shape[0]*2)\n",
    "plt.xticks(index+0.15, df_bar['Store Name'],rotation=45)\n",
    "plt.ylabel('Popularity')\n",
    "plt.title('Store Popularity ' + df_currentpopularity.loc[:,'current_datetime_gmt'].max())\n",
    "ax.legend() \n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 76,
   "metadata": {},
   "outputs": [],
   "source": [
    "#Append output to csv\n",
    "with open('Store_Popularity.csv', 'a') as f:\n",
    "    df_currentpopularity.to_csv(f, header=f.tell()==0, index=False, line_terminator='\\n')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 88,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<style  type=\"text/css\" >\n",
       "    #T_46d19066_6f4b_11e9_aa06_e8113250c0fdrow0_col0 {\n",
       "            width:  500px;\n",
       "        }    #T_46d19066_6f4b_11e9_aa06_e8113250c0fdrow1_col0 {\n",
       "            width:  500px;\n",
       "        }    #T_46d19066_6f4b_11e9_aa06_e8113250c0fdrow2_col0 {\n",
       "            width:  500px;\n",
       "        }    #T_46d19066_6f4b_11e9_aa06_e8113250c0fdrow3_col0 {\n",
       "            width:  500px;\n",
       "        }    #T_46d19066_6f4b_11e9_aa06_e8113250c0fdrow4_col0 {\n",
       "            width:  500px;\n",
       "        }    #T_46d19066_6f4b_11e9_aa06_e8113250c0fdrow5_col0 {\n",
       "            width:  500px;\n",
       "        }    #T_46d19066_6f4b_11e9_aa06_e8113250c0fdrow6_col0 {\n",
       "            width:  500px;\n",
       "        }</style><table id=\"T_46d19066_6f4b_11e9_aa06_e8113250c0fd\" ><thead>    <tr>        <th class=\"blank level0\" ></th>        <th class=\"col_heading level0 col0\" >data</th>        <th class=\"col_heading level0 col1\" >name</th>    </tr></thead><tbody>\n",
       "                <tr>\n",
       "                        <th id=\"T_46d19066_6f4b_11e9_aa06_e8113250c0fdlevel0_row0\" class=\"row_heading level0 row0\" >0</th>\n",
       "                        <td id=\"T_46d19066_6f4b_11e9_aa06_e8113250c0fdrow0_col0\" class=\"data row0 col0\" >[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 24, 36, 35, 29, 29, 27, 20, 21, 25, 19, 6, 0, 0]</td>\n",
       "                        <td id=\"T_46d19066_6f4b_11e9_aa06_e8113250c0fdrow0_col1\" class=\"data row0 col1\" >Monday</td>\n",
       "            </tr>\n",
       "            <tr>\n",
       "                        <th id=\"T_46d19066_6f4b_11e9_aa06_e8113250c0fdlevel0_row1\" class=\"row_heading level0 row1\" >1</th>\n",
       "                        <td id=\"T_46d19066_6f4b_11e9_aa06_e8113250c0fdrow1_col0\" class=\"data row1 col0\" >[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12, 23, 30, 31, 30, 27, 21, 15, 21, 34, 25, 5, 0, 0]</td>\n",
       "                        <td id=\"T_46d19066_6f4b_11e9_aa06_e8113250c0fdrow1_col1\" class=\"data row1 col1\" >Tuesday</td>\n",
       "            </tr>\n",
       "            <tr>\n",
       "                        <th id=\"T_46d19066_6f4b_11e9_aa06_e8113250c0fdlevel0_row2\" class=\"row_heading level0 row2\" >2</th>\n",
       "                        <td id=\"T_46d19066_6f4b_11e9_aa06_e8113250c0fdrow2_col0\" class=\"data row2 col0\" >[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 17, 27, 31, 28, 21, 18, 24, 33, 32, 19, 6, 0, 0]</td>\n",
       "                        <td id=\"T_46d19066_6f4b_11e9_aa06_e8113250c0fdrow2_col1\" class=\"data row2 col1\" >Wednesday</td>\n",
       "            </tr>\n",
       "            <tr>\n",
       "                        <th id=\"T_46d19066_6f4b_11e9_aa06_e8113250c0fdlevel0_row3\" class=\"row_heading level0 row3\" >3</th>\n",
       "                        <td id=\"T_46d19066_6f4b_11e9_aa06_e8113250c0fdrow3_col0\" class=\"data row3 col0\" >[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 18, 28, 34, 33, 27, 23, 27, 36, 36, 24, 9, 0, 0]</td>\n",
       "                        <td id=\"T_46d19066_6f4b_11e9_aa06_e8113250c0fdrow3_col1\" class=\"data row3 col1\" >Thursday</td>\n",
       "            </tr>\n",
       "            <tr>\n",
       "                        <th id=\"T_46d19066_6f4b_11e9_aa06_e8113250c0fdlevel0_row4\" class=\"row_heading level0 row4\" >4</th>\n",
       "                        <td id=\"T_46d19066_6f4b_11e9_aa06_e8113250c0fdrow4_col0\" class=\"data row4 col0\" >[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 33, 48, 42, 36, 38, 38, 40, 51, 59, 43, 16, 0, 0]</td>\n",
       "                        <td id=\"T_46d19066_6f4b_11e9_aa06_e8113250c0fdrow4_col1\" class=\"data row4 col1\" >Friday</td>\n",
       "            </tr>\n",
       "            <tr>\n",
       "                        <th id=\"T_46d19066_6f4b_11e9_aa06_e8113250c0fdlevel0_row5\" class=\"row_heading level0 row5\" >5</th>\n",
       "                        <td id=\"T_46d19066_6f4b_11e9_aa06_e8113250c0fdrow5_col0\" class=\"data row5 col0\" >[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 27, 58, 73, 74, 87, 100, 84, 59, 60, 58, 23, 0, 0, 0]</td>\n",
       "                        <td id=\"T_46d19066_6f4b_11e9_aa06_e8113250c0fdrow5_col1\" class=\"data row5 col1\" >Saturday</td>\n",
       "            </tr>\n",
       "            <tr>\n",
       "                        <th id=\"T_46d19066_6f4b_11e9_aa06_e8113250c0fdlevel0_row6\" class=\"row_heading level0 row6\" >6</th>\n",
       "                        <td id=\"T_46d19066_6f4b_11e9_aa06_e8113250c0fdrow6_col0\" class=\"data row6 col0\" >[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 53, 77, 70, 67, 56, 25, 0, 0, 0, 0, 0, 0]</td>\n",
       "                        <td id=\"T_46d19066_6f4b_11e9_aa06_e8113250c0fdrow6_col1\" class=\"data row6 col1\" >Sunday</td>\n",
       "            </tr>\n",
       "    </tbody></table>"
      ],
      "text/plain": [
       "<pandas.io.formats.style.Styler at 0x2190b571438>"
      ]
     },
     "execution_count": 88,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#Check normal hours of particular store\n",
    "place_id_test = 'ChIJvUYBYLuue0gRKwHtN1aAiN4'\n",
    "df_normalhours = df_populartimes[df_populartimes['id']==place_id_test]\n",
    "df_normalhours = json_normalize(df_normalhours['populartimes'][df_normalhours.index.values[0]], errors = 'ignore')\n",
    "df_normalhours = df_normalhours.style.set_properties(subset=['data'], **{'width': '500px'})\n",
    "df_normalhours"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#populartimes.get('AIzaSyBTqRFNpFXp2r8o0lk6tbGIU92_35caKSU',['clothing_store'],(51.51568529999999,-0.1416379),(51.5156853,-0.1416379), radius=100)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
